// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CIneData.Models;

public partial class Entrada
{
    public int IdButaca { get; set; }

    public int IdFuncion { get; set; }

    public int? IdReserva { get; set; }

    public virtual Butaca IdButacaNavigation { get; set; }

    public virtual Funcione IdFuncionNavigation { get; set; }

    [JsonIgnore]
    public virtual Reserva IdReservaNavigation { get; set; }
}