// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CIneData.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace CIneData.Models
{
    public partial interface ICineDbContextProcedures
    {
        Task<List<EncontrarConflictoResult>> EncontrarConflictoAsync(DateTime? Horario, int? IdPelicula, int? IdSala, int? idFuncion, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
