// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DataAPI.Data.Models;

public partial class TTurno
{
    public int Id { get; set; }

    public DateTime Fecha { get; set; }

    public string Cliente { get; set; }

    public DateTime? FechaBaja { get; set; }

    public string MotivoBaja { get; set; }
    public virtual ICollection<TDetallesTurno> TDetallesTurnos { get; set; } = new List<TDetallesTurno>();
}