// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EFBancoAPI.Data.Models;

public partial class Cuenta
{
    public int Id { get; set; }

    public string Cbu { get; set; }

    public decimal? Saldo { get; set; }

    public int? TipoCuentaId { get; set; }

    public DateTime? UltimoMovimiento { get; set; }

    public int? ClienteId { get; set; }

    public DateTime? FechaBaja { get; set; }

    public string MotivoBaja { get; set; }
    //[JsonIgnore]
    public virtual Cliente Cliente { get; set; }
    //[JsonIgnore]
    public virtual TipoCuenta TipoCuenta { get; set; }


    public bool IsValid()
    {
        if(string.IsNullOrEmpty(Cbu) || TipoCuentaId < 1 || UltimoMovimiento > DateTime.Now || ClienteId < 1)
            return false;
        return true;
    }

    public bool IsValidNew()
    {
        if (Id != 0 || string.IsNullOrEmpty(Cbu) || TipoCuentaId < 1 || UltimoMovimiento > DateTime.Now || ClienteId < 1)
            return false;
        return true;
    }
}